apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter-service-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/willjschmitt/fintech-devcon-2022-gitops.git
    targetRevision: HEAD
    path: config/greeter-service-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter-service-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/willjschmitt/fintech-devcon-2022-gitops.git
    targetRevision: HEAD
    path: config/greeter-service-production
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
